### ISSUE TITLE
Meeting Minutes - Mar 3, 2021

### ISSUE THREAD

**Issue by ssyayayy** [UBC-MDS/coRPysprofiling#17]
The following are the to-do tasks for Milestone 2:
1. Write test cases and code iteratively. Assigned functions to individual team members.
- corpus_analysis - Anita
- corpus_viz - Ivy
- corpora_compare - Elanor
- corpora_best_match (with a helper function) - Junghoo

2. Create project structure for the R project - Ivy
3. Write R function documentation (e.g., complete roxygen2 comments)
- corpus_analysis - Anita
- corpus_viz - Ivy
- corpora_compare - Elanor
- corpora_best_match (with a helper function) - Junghoo

Please feel free to add anything I may have missed in the comments.

**Comment by jkim222383** [comment]
https://github.com/UBC-MDS/coRPysprofiling/pull/18

**Comment by ssyayayy** [comment]
Created project structure for the R project. Here is the link:
https://github.com/UBC-MDS/coRPysprofiling-R
