### ISSUE TITLE
License checklist

### ISSUE THREAD

**Issue by eboylestanley** [UBC-MDS/coRPysprofiling#48]

**Comment by jkim222383** [comment]
Licenses for libraries used:
- base Python is GPL-compatible 
- [`nltk`](https://pypi.org/project/nltk/) is licensed under Apache 2
- [`altair`](https://pypi.org/project/altair/) is licensed under BSD

**Comment by eboylestanley** [comment]
- [`sentence-transformers`](https://pypi.org/project/sentence-transformers/) is licensed under Apache 2:

**Comment by ssyayayy** [comment]
- [`wordcloud`](https://pypi.org/project/wordcloud/) is licensed under MIT
- [`matplotlib`](https://pypi.org/project/matplotlib/) is licensed under PSF (Python Software Foundation) License

**Comment by AnitaLi-0371** [comment]
- [`pandas`](https://pypi.org/project/pandas/) is licensed under BSD
- [`numpy`](https://pypi.org/project/numpy/) is licensed under BSD

**Comment by jkim222383** [comment]
MIT license is compatible with all of the licenses listed above, including GPL. 

Python Software Foundation license is compatible with GPL [Source](https://docs.python.org/3/license.html#psf-license-agreement-for-python-release)

Apache 2 is compatible with GPLv3, but the resulting work should be published under GPLv3 license, as indicated here:

> Apache 2 software can therefore be included in GPLv3 projects, because the GPLv3 license accepts our software into GPLv3 works. However, GPLv3 software cannot be included in Apache projects. The licenses are incompatible in one direction only, and it is a result of ASF's licensing philosophy and the GPLv3 authors' interpretation of copyright law. [Source](https://www.apache.org/licenses/GPL-compatibility.html)

BSD is compatible with GPLv3 as well. [Souce](https://www.gnu.org/licenses/license-list.en.html)

So it makes sense to publish our work under GPLv3 license.

**Comment by jkim222383** [comment]
https://github.com/UBC-MDS/coRPysprofiling/commit/b02af2dc6bff4e62f061760999e2e0e10eab363e
